name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure
        run: |
          cmake -B build \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DSPACROW_ENABLE_CODSPEED=OFF \
                -DSPACROW_CODSPEED_MODE=OFF \
                -DFETCH_DEPENDENCIES_WITH_CMAKE=ON

      - name: Build tests
        run: cmake --build build/ --target spacrow_tests

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
