name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -e -l {0}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: 16
          platform: x64

      - name: Checkout
        uses: actions/checkout@v7

      - name: Set conda environment
        uses: mamba-org/setup-micromamba@main
        with:
          environment-name: myenv
          environment-file: environment-dev.yml
          init-shell: bash
          cache-downloads: true

      - name: Configure
        run: |
          cmake -B build \
                -G Ninja \
                -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
                -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DSPARROW_COMPUTE_ENABLE_CODSPEED=OFF \
                -DSPARROW_COMPUTE_CODSPEED_MODE=OFF \
                -DFETCH_DEPENDENCIES_WITH_CMAKE=OFF

      - name: Build tests
        run: cmake --build build/ --target sparrow-compute_tests

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
